name: Docker

on:
  push:
    branches: [ twim-deploy ]
  pull_request:
    branches: [ twim-deploy ]

jobs:

    deploy:

        name: Setup Gcloud Account
        runs-on: ubuntu-latest
        env:
          IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}
        steps:

        - name: Login
          uses: google-github-actions/setup-gcloud@v0
          with:
            project_id: ${{ secrets.GCP_PROJECT_ID }}
            service_account_email: ${{ secrets.GCP_EMAIL }}
            service_account_key: ${{ secrets.GCP_CREDENTIALS }}

        - name: Configure Docker
          run: gcloud auth configure-docker --quiet

        - name: Checkout repository
          uses: actions/checkout@v3
          with:
            ref: twim-deploy

        - name: Decrypt the secrets
          env:
            GCE_ENV_DOCKER: ${{ secrets.GCE_ENV_DOCKER }}
            GCE_CONFIG_FIREBASE_ADMIN_JSON: ${{ secrets.GCE_CONFIG_FIREBASE_ADMIN_JSON }}
          run: |
            echo $GCE_ENV_DOCKER | base64 --decode > .env-docker
            echo $GCE_CONFIG_FIREBASE_ADMIN_JSON | base64 --decode > ./config/firebase-admin.json

        - name: Build Docker image
          run: source .env-docker && docker build -f Dockerfile.prod . -t $IMAGE_NAME

        - name: Push Docker image
          run: docker push $IMAGE_NAME

        - name: Deploy Docker image
          run: gcloud run deploy ${{ secrets.GCP_PROJECT_ID }} --image $IMAGE_NAME --region us-central1 --platform managed