name: Docker

on:
  push:
    branches: [twim-deploy]
  pull_request:
    branches: [twim-deploy]

jobs:
  deploy:
    name: Setup Gcloud Account
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: gcr.io/twim-knowledge-350317/api-twim-knowledge
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: twim-deploy

      - id: "auth"
        name: "Authenticate to Google cloud."
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCE_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Decrypt the secrets
        env:
          GCE_ENV_DOCKER: ${{ secrets.GCE_ENV_DOCKER }}
          GCE_CONFIG_FIREBASE_ADMIN_JSON: ${{ secrets.GCE_CONFIG_FIREBASE_ADMIN_JSON }}
        run: |
          echo $GCE_ENV_DOCKER | base64 --decode > .env-docker
          echo $GCE_CONFIG_FIREBASE_ADMIN_JSON | base64 --decode > ./config/firebase-admin.json

      - name: Build Docker image
        run: source .env-docker && docker build -f Dockerfile.prod . -t $IMAGE_NAME

      - name: Push Docker image
        run: docker push $IMAGE_NAME

      - name: Deploy Docker image
        run: gcloud run deploy twim-knowledge-350317 --image $IMAGE_NAME --region us-central1 --platform managed
